### ISSUE TITLE
Italic variant

### ISSUE THREAD

**Issue by parzival-cmd** [uxigene/onest#1]
Hi are there any plans for the italic weight?

**Comment by uxigene** [comment]
Hello @parzival-cmd I can’t answer this question as I’m not the font developer. I created only the font face css as it was missing in their distribution from https://onest.md/ But I forwarded your question to them.

**Comment by parzival-cmd** [comment]
Thanks, much appreciated.

**Comment by parzival-cmd** [comment]
Hi @uxigene , how can I contact them from my side?

**Comment by uxigene** [comment]
Try Telegram [@onest_font_md](https://t.me/onest_font_md)
