### ISSUE TITLE
OTF version

### ISSUE THREAD

**Issue by maa7** [uxigene/onest#2]
Hello,
Please release font with PostScript/CFF outlines (*.OTF) with psautohint.
On Windows without smoothing, the OTF version of the font at small sizes looks much better than the TTF version.
For example:
![ss3_ttf_otf](https://github.com/uxigene/onest/assets/45234995/f097c5ea-d1ed-40b0-8a0c-d138805fe3c3)
![fs_ttf_otf](https://github.com/uxigene/onest/assets/45234995/9f28f100-fd5a-4fac-8251-37816a896d44)

**Comment by uxigene** [comment]
Hello @maa7. Unfortunately the .otf version is missing in the distribution package from https://onest.md/

Please note that I'm not font developer. I just created the font-face as it was missing from their distribution package. If you have any font related issues try asking here: https://github.com/simpals/onest
